# Assignment

-------------

**1) Complete this notebook and make a pull request:** 

Answer questions (Q) in the space provided (A) in this notebook. When finished, copy your notebook to the `Assignment/` directory and name it `nb-6.5-<Github-username>.ipynb`. Then make a pull request to the upstream repo. The entered answers in this notebook will be simply Markdown text where I want you to interpret and describe a block of code to better understand what it is doing. Much of this code you will have seen already. 


**2) Write an importable Python package, save as a repo, and test it here.**

The package should be written as we did in our last lession (`.py` files in a directory with a setup.py file so it can be installed with `pip`). Follow instructions at the end of this notebook for how to write your package. Test it here by importing the package and executing the code at the end. It should work and give correct answers, if not, continue working on it. When you have it completed save your package as a new Github repo named `seqlib`.

### The `seqlib` package

Together we are going to write several functions here that will make up your new package called `seqlib`. It will be your job to copy these functions, organize them into a Class, save the code into a `.py` file (you can use SublimeText if you're comfortable with it for much of this, or any text editor including the one in jupyter), package the files so they can be imported as a library, and test the package so that it accomplishes the tasks which are defined at the end of this notebook. First things first, though, let's write the functions. 

In [1]:
import numpy as np
import pandas as pd

### Q.  Describe what the `mutate()` function below does:


A. This function takes a single input base and "mutates" it to a different base.

In [2]:
def mutate(base):                        #begin fxn, base input required
    diff = set("ACTG") - set(base)       #create a population that does not include input base
    return np.random.choice(list(diff))  #sample n=1 from this population

In [18]:
# test it
mutate("A")

'G'

In [33]:
mutate("AT") #only one base returned. base is always either G or C

'G'

In [34]:
mutate("ATTTAGC") #nope

ValueError: a must be non-empty

### Q. Describe how the `seqdata()` function below works:
Annotate the code by inserting lines with comments as you read through the function to make sense of it. What is being created at each step and how is it used?


A. this function simulates an array of sequences with indels and point mutations. it takes two inputs: ninds, the number of sequences to generate; and nsites, the length of the sequences to generate

In [58]:
ninds = 5
nsites = 10
oseq = np.random.choice(list("ACGT"), size=nsites)    #original seq? get a random seq of length = nsites
arr = np.array([oseq for i in range(ninds)]) 
print(oseq)
print(arr)

['G' 'C' 'G' 'T' 'G' 'T' 'T' 'G' 'A' 'A']
[['G' 'C' 'G' 'T' 'G' 'T' 'T' 'G' 'A' 'A']
 ['G' 'C' 'G' 'T' 'G' 'T' 'T' 'G' 'A' 'A']
 ['G' 'C' 'G' 'T' 'G' 'T' 'T' 'G' 'A' 'A']
 ['G' 'C' 'G' 'T' 'G' 'T' 'T' 'G' 'A' 'A']
 ['G' 'C' 'G' 'T' 'G' 'T' 'T' 'G' 'A' 'A']]


In [59]:
muts = np.random.binomial(1, 0.1, (ninds, nsites)) 
print(muts)

for col in range(nsites):
    newbase = mutate(arr[0, col])
    mask = muts[:, col].astype(bool)
    arr[:, col][mask] = newbase

[[0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [61]:
print(oseq)
newbase = mutate(oseq[0])
print(newbase)

print(range(ninds))
print(col)
mask = muts[:, col].astype(bool)
print(mask)

['G' 'C' 'G' 'T' 'G' 'T' 'T' 'G' 'A' 'A']
T
range(0, 5)
9
[False False False False False]


In [63]:
missing = np.random.binomial(1, 0.1, (ninds, nsites))
arr[missing.astype(bool)] = "N"
print(arr)

[['G' 'C' 'N' 'N' 'G' 'N' 'A' 'G' 'A' 'N']
 ['G' 'C' 'G' 'T' 'G' 'T' 'T' 'G' 'A' 'N']
 ['N' 'C' 'G' 'T' 'N' 'T' 'N' 'N' 'A' 'A']
 ['G' 'C' 'G' 'N' 'G' 'A' 'T' 'A' 'A' 'A']
 ['G' 'C' 'G' 'T' 'G' 'T' 'T' 'G' 'A' 'A']]


In [75]:
def simulate(ninds, nsites):                              #define fxn, two inputs
    oseq = np.random.choice(list("ACGT"), size=nsites)    #original seq? get a random seq of length = nsites
    arr = np.array([oseq for i in range(ninds)])          #create an array by duplicating oseq into number of rows = ninds
    muts = np.random.binomial(1, 0.1, (ninds, nsites))    #create a integer boolean mask using binomial. mutation rate = 0.1
    for col in range(nsites):                             #for i in each integer in nsites,
        newbase = mutate(arr[0, col])    #mutate each base in seq... could have done newbase = mutate(oseq[col])? any difference?
        mask = muts[:, col].astype(bool)                  #convert integer mask to actual bool mask
        arr[:, col][mask] = newbase                       #convert arr position to newbase only if the mutation mask is true
    missing = np.random.binomial(1, 0.1, (ninds, nsites)) #creates missing values.... simulation of indels?
    arr[missing.astype(bool)] = "N"                       #returns missing values as N
    return arr

In [76]:
seqs = simulate(6, 15)
print(seqs)

[['N' 'C' 'N' 'G' 'C' 'C' 'A' 'T' 'G' 'C' 'C' 'N' 'G' 'T' 'G']
 ['N' 'C' 'T' 'G' 'C' 'N' 'C' 'G' 'C' 'C' 'C' 'G' 'G' 'A' 'G']
 ['T' 'C' 'N' 'G' 'C' 'C' 'N' 'T' 'N' 'G' 'C' 'G' 'N' 'T' 'G']
 ['T' 'C' 'T' 'G' 'C' 'C' 'A' 'T' 'G' 'C' 'C' 'G' 'T' 'A' 'G']
 ['T' 'C' 'T' 'G' 'C' 'C' 'A' 'T' 'G' 'C' 'C' 'G' 'G' 'T' 'G']
 ['T' 'C' 'T' 'G' 'T' 'N' 'A' 'T' 'G' 'C' 'C' 'G' 'G' 'T' 'G']]


### **Q: Describe how the `filter_missing` function works:**
Annotate the code by inserting lines with comments as you read through the function to make sense of it. How does it find columns with missing (N) values in them? How might you mprove it?

A. this filters the sequences based on indel frequency. if the frequency of missing N values in any column in arr is higher than maxfreq, it is not returned

In [72]:
print(np.sum(arr == "N", axis=0))
print(np.sum(arr == "N", axis=0)/arr.shape[0])

maxfreq = 0.1
freqmissing = np.sum(arr == "N", axis=0) / arr.shape[0]
print(arr[:, freqmissing <= maxfreq])

[1 0 1 2 1 1 1 1 0 2]
[0.2 0.  0.2 0.4 0.2 0.2 0.2 0.2 0.  0.4]
[['C' 'A']
 ['C' 'A']
 ['C' 'A']
 ['C' 'A']
 ['C' 'A']]


In [73]:
def filter_missing(arr, maxfreq):                            #def fxn two inputs; one is arr from above?
    freqmissing = np.sum(arr == "N", axis=0) / arr.shape[0]  #total frequency of indels per column?
    return arr[:, freqmissing <= maxfreq]                    #filter cols with indel frequency higher than input, maxfreq

In [78]:
filter_missing(seqs, 0.1)

array([['C', 'G', 'C', 'T', 'C', 'C', 'T', 'G'],
       ['C', 'G', 'C', 'G', 'C', 'C', 'A', 'G'],
       ['C', 'G', 'C', 'T', 'G', 'C', 'T', 'G'],
       ['C', 'G', 'C', 'T', 'C', 'C', 'A', 'G'],
       ['C', 'G', 'C', 'T', 'C', 'C', 'T', 'G'],
       ['C', 'G', 'T', 'T', 'C', 'C', 'T', 'G']], dtype='<U1')

### **Q: Describe how the `filter_maf` function works:**
Annotate the code by inserting lines with comments as you read through the function to make sense of it. How does it calculate minor allele frequencies? Why does it use copy?

A. this function filters the array by first calculating the allele frequency and then selecting the minor (>0.5) frequency.

In [89]:
print(arr)
print(arr != arr[0])

print(np.sum(arr != arr[0], axis=0)) #/ arr.shape[0]

maf = freqs.copy()                                       #makes a copy of this value...
    maf[maf > 0.5] = 1 - maf[maf > 0.5] 

[['G' 'C' 'N' 'N' 'G' 'N' 'A' 'G' 'A' 'N']
 ['G' 'C' 'G' 'T' 'G' 'T' 'T' 'G' 'A' 'N']
 ['N' 'C' 'G' 'T' 'N' 'T' 'N' 'N' 'A' 'A']
 ['G' 'C' 'G' 'N' 'G' 'A' 'T' 'A' 'A' 'A']
 ['G' 'C' 'G' 'T' 'G' 'T' 'T' 'G' 'A' 'A']]
[[False False False False False False False False False False]
 [False False  True  True False  True  True False False False]
 [ True False  True  True  True  True  True  True False  True]
 [False False  True False False  True  True  True False  True]
 [False False  True  True False  True  True False False  True]]
[1 0 4 3 1 4 4 2 0 3]


In [97]:
freqs = np.sum(arr != arr[0], axis=0) / arr.shape[0]
maf = freqs.copy()   #makes a copy of this value...
print(maf)

minfreq = 0.1
maf[maf > 0.5] = 1 - maf[maf > 0.5]
print(maf)
print(arr[:, maf > minfreq])

[0.2 0.  0.8 0.6 0.2 0.8 0.8 0.4 0.  0.6]
[0.2 0.  0.2 0.4 0.2 0.2 0.2 0.4 0.  0.4]
[['G' 'N' 'N' 'G' 'N' 'A' 'G' 'N']
 ['G' 'G' 'T' 'G' 'T' 'T' 'G' 'N']
 ['N' 'G' 'T' 'N' 'T' 'N' 'N' 'A']
 ['G' 'G' 'N' 'G' 'A' 'T' 'A' 'A']
 ['G' 'G' 'T' 'G' 'T' 'T' 'G' 'A']]


In [99]:
def filter_maf(arr, minfreq):                                #minor allele frequency... MAF? input is arr and given minfreq
    freqs = np.sum(arr != arr[0], axis=0) / arr.shape[0]  #adds up number of times the first seq matches the rest in the array
    maf = freqs.copy()                                       #makes a copy of this value...
    maf[maf > 0.5] = 1 - maf[maf > 0.5]          #actually get minor allele freq. if freq cal'd above is >0.5, do 1-freq
    return arr[:, maf > minfreq]                     #return all rows of arr if the MAF is greater than 0.1. (cutoff is QC?)

In [100]:
filter_maf(seqs, 0.1)

array([['N', 'N', 'C', 'C', 'A', 'T', 'G', 'C', 'N', 'G', 'T'],
       ['N', 'T', 'C', 'N', 'C', 'G', 'C', 'C', 'G', 'G', 'A'],
       ['T', 'N', 'C', 'C', 'N', 'T', 'N', 'G', 'G', 'N', 'T'],
       ['T', 'T', 'C', 'C', 'A', 'T', 'G', 'C', 'G', 'T', 'A'],
       ['T', 'T', 'C', 'C', 'A', 'T', 'G', 'C', 'G', 'G', 'T'],
       ['T', 'T', 'T', 'N', 'A', 'T', 'G', 'C', 'G', 'G', 'T']],
      dtype='<U1')

### Q: What order should these functions be applied, does it matter?

A. it seems like both arrays are identical, regardless of order. However, I feel that the filter_missing function should probably be applied before the filter_maf function, to form a pipeline of first QC and then analysis. THis corresponds to the second cell below

In [101]:
filter_missing(filter_maf(seqs, 0.1), 0.1)

array([['C', 'T', 'C', 'T'],
       ['C', 'G', 'C', 'A'],
       ['C', 'T', 'G', 'T'],
       ['C', 'T', 'C', 'A'],
       ['C', 'T', 'C', 'T'],
       ['T', 'T', 'C', 'T']], dtype='<U1')

In [102]:
filter_maf(filter_missing(seqs, 0.1), 0.1)

array([['C', 'T', 'C', 'T'],
       ['C', 'G', 'C', 'A'],
       ['C', 'T', 'G', 'T'],
       ['C', 'T', 'C', 'A'],
       ['C', 'T', 'C', 'T'],
       ['T', 'T', 'C', 'T']], dtype='<U1')

### Q: Describe how `calculate_statistics()` works


A. calculates a bunch of biologically relevant statistics using array np functions

In [107]:
np.var(arr == arr[0], axis=0)

array([0.16, 0.  , 0.16, 0.24, 0.16, 0.16, 0.16, 0.24, 0.  , 0.24])

In [116]:
print(arr)

print(np.sum(arr != arr[0], axis=0))

print(np.mean(np.sum(arr != arr[0], axis=0)))

print(arr.shape[0])
print(np.mean(np.sum(arr != arr[0], axis=0) / arr.shape[0]))

[['G' 'C' 'N' 'N' 'G' 'N' 'A' 'G' 'A' 'N']
 ['G' 'C' 'G' 'T' 'G' 'T' 'T' 'G' 'A' 'N']
 ['N' 'C' 'G' 'T' 'N' 'T' 'N' 'N' 'A' 'A']
 ['G' 'C' 'G' 'N' 'G' 'A' 'T' 'A' 'A' 'A']
 ['G' 'C' 'G' 'T' 'G' 'T' 'T' 'G' 'A' 'A']]
[1 0 4 3 1 4 4 2 0 3]
2.2
5
0.43999999999999995


In [120]:
print(np.any(arr != arr[0], axis=0))
np.any(arr != arr[0], axis=0).sum()

[ True False  True  True  True  True  True  True False  True]


8

In [12]:
def calculcate_statistics(arr):                                #fxn takes arr as arg
    nd = np.var(arr == arr[0], axis=0).mean()                  #mean nt diversity: mean of variance values of each row
    mf = np.mean(np.sum(arr != arr[0], axis=0) / arr.shape[0]) #mean minor allele freq: sum # not = first row, divide by $# rows, take mean
    inv = np.any(arr != arr[0], axis=0).sum()                  #invariant sites: count num not equal to first seq?
    var = arr.shape[1] - inv                                   #variable sites: num cols - num not equal to first seq?
    return pd.Series(
        {"mean nucleotide diversity": nd,
         "mean minor allele frequency": mf,
         "invariant sites": inv,
         "variable sites": var,
        })

In [13]:
calculcate_statistics(seqs)

invariant sites                12.000000
mean minor allele frequency     0.255556
mean nucleotide diversity       0.150000
variable sites                  3.000000
dtype: float64

### Instructions: Write a `seqlib` Class object

I started writing the bare bones of it below. You should write it so that it can be executed as described below to perform all of the functions we defined above, and so that its attributes can be accessed. Save this class object in a `.py` file and make it into an importable package called `seqlib`. You can write and test your object in this notebook if you like, but it must be saved separately in a `.py` file and be imported. You cannot execute the code at the end using your object defined here in the notebook. When finished save your package to GitHub as a repo just like we did with the `helloworld` package. You do not need to write a CLI script like we did for the `helloworld` package, we will only be using the Python API here. See the examples below for **how you should write your Class object**. It should be able to run in the way written below, so look at that code and think about how you would write a Class object that can do that. 

While you can mostly copy the functions from above, you will need to modify them slightly to access information about the Class object using *self*. For example, the `simulate()` function below takes self as a first argument and can access `self.inds` and `self.nsites` from that, so we do not need to provide those as arguments to the `simulate` function like we did above. 

In [137]:
import numpy as np
import pandas as pd

In [168]:
class Seqlib:
    def __init__(self, ninds, nsites): #no minfreq and maxfreq?
        self.ninds = ninds
        self.nsites = nsites
        #self.maxfreq = maxfreq    #this did not work...
        #self.minfreq = minfreq
        #self.arr = None
        #self.PD = None
        self.seqs = self.simulate(ninds, nsites)
        
    def mutate(self, base):
        diff = set("ACTG") - set(base)
        return np.random.choice(list(diff))
        
    def simulate(self):
        oseq = np.random.choice(list("ACGT"), size=self.nsites)    #original seq? get a random seq of length = nsites
        arr = np.array([oseq for i in range(self.ninds)])          #create an array by duplicating oseq into number of rows = ninds
        muts = np.random.binomial(1, 0.1, (self.ninds, self.nsites))    #create a integer boolean mask using binomial. mutation rate = 0.1
        for col in range(self.nsites):                             #for i in each integer in nsites,
            newbase = mutate(arr[0, col])    #mutate each base in seq... could have done newbase = mutate(oseq[col])? any difference?
            mask = muts[:, col].astype(bool)                  #convert integer mask to actual bool mask
            arr[:, col][mask] = newbase                       #convert arr position to newbase only if the mutation mask is true
        missing = np.random.binomial(1, 0.1, (self.ninds, self.nsites)) #creates missing values.... simulation of indels?
        arr[missing.astype(bool)] = "N"                       #returns missing values as N
        return arr
        #self.arr = arr #this did not work

    def filter_missing(arr, maxfreq):                            #def fxn two inputs; one is arr from above?
        freqmissing = np.sum(arr == "N", axis=0) / arr.shape[0]  #total frequency of indels per column?
        arr[:, freqmissing <= maxfreq]                    #filter cols with indel frequency higher than input, maxfreq
        #self.arr = arr[:, freqmissing <= maxfreq]
        return arr
        
    def filter_maf(arr, minfreq):                                #minor allele frequency... MAF? input is arr and given minfreq
        freqs = np.sum(arr != arr[0], axis=0) / arr.shape[0]  #adds up number of times the first seq matches the rest in the array
        maf = freqs.copy()                                       #makes a copy of this value...
        maf[maf > 0.5] = 1 - maf[maf > 0.5]          #actually get minor allele freq. if freq cal'd above is >0.5, do 1-freq
        return arr[:, maf > minfreq]                     #return all rows of arr if the MAF is greater than 0.1. (cutoff is QC?)
        #self.arr = arr[:, maf > minfreq]

    def maf(self):
        arr = self.simulate()  #gen array
        freqs = np.sum(arr != arr[0], axis=0) / arr.shape[0] #adds up number of times the first seq matches the rest in the array
        maf = freqs.copy()
        maf[maf > 0.5] = 1 - maf[maf > 0.5]               #get minor allele freq. if freq cal'd above is >0.5, do 1-freq
        return freqs
        
    def filter(self, minfreq, maxfreq):
        maf = self.filter_maf(self.filter_missing(maxfreq), minfreq)
        return maf    
        
    def calculcate_statistics(self):                                #fxn takes arr as arg
        nd = np.var(arr == arr[0], axis=0).mean()                  #mean nt diversity: mean of variance values of each row
        mf = np.mean(np.sum(arr != arr[0], axis=0) / arr.shape[0]) #mean minor allele freq: sum # not = first row, divide by $# rows, take mean
        inv = np.any(arr != arr[0], axis=0).sum()                  #invariant sites: count num not equal to first seq?
        var = arr.shape[1] - inv                                   #variable sites: num cols - num not equal to first seq?
        return pd.Series(
            {"mean nucleotide diversity": nd,
             "mean minor allele frequency": mf,
             "invariant sites": inv,
             "variable sites": var,
            })

In [169]:
seqs = Seqlib(ninds = 10, nsites = 50)
seqs

TypeError: simulate() takes 1 positional argument but 3 were given

## Test your package
The package should be globally importable (you ran `pip install .` or `pip install -e .` to install it), and it should be able to execute the following code without error. 

In [171]:
import seqlib

In [172]:
# init a Seqlib Class object
seqs = seqlib.Seqlib(ninds=10, nsites=50)

TypeError: simulate() takes 1 positional argument but 3 were given

In [173]:
# access attributes from the object
print(seqs.ninds, seqs.nsites)

10 50


In [ ]:
# returns the MAF of the array as an array of floats
seqs.maf

In [ ]:
# return a view of the filtered sequence array by applying a new function 
# called `filter()` that applies both the maf and missing filter functions
seqs.filter(minmaf=0.1, maxmissing=0.0)

In [ ]:
# calculate statistics for an array with the results returned as a DataFrame
seqs.calculate_statistics()

In [ ]:
# calculate statistics for an array after filtering it
seqs.filter(minmaf=0.1, maxmissing=0.0).calculate_statistics()